#!/bin/sh

git_dir="$(git rev-parse --git-dir)"
git_repo_hooks_dir="$(pwd)/${git_dir}/hooks"

. "${git_repo_hooks_dir}/git_hooks_shell_init_leadin"

RUBY_BIN="$(which ruby)"

[ -x "${RUBY_BIN}" ] && {
  "${RUBY_BIN}" "${GIT_HOOKS_DIR}/scriptlets_prepare-commit-msg/run_vcproj2cmake_tests.rb" || exit 1
  "${RUBY_BIN}" "${GIT_HOOKS_DIR}/scriptlets_prepare-commit-msg/grep_problematic_content.rb" || exit 1
}

# Add an optional hook to execute potentially available local tests
local_tests_sh="${git_repo_hooks_dir}/run_vcproj2cmake_tests_local.sh"
[ -f "${local_tests_sh}" ] && {
  . "${local_tests_sh}"
}

exit 0
