# This sample file is provided by the vcproj2cmake build converter (vcproj2cmake.sf.net)
# It provides automatic vcproj2cmake integration for user-side projects,
# i.e. without a user being required to manually download vcproj2cmake.
# Usage: permanently copy this file to your source tree
# (ideally your CMake module path, i.e. SOURCE_ROOT/cmake/Modules/),
# then include() it somewhere from your existing other CMake config parts.
# Upon a build run this code will then automatically fetch the vcproj2cmake
# git repository and do a conversion run of all Visual Studio projects.
# If your project further is prepared to automatically include the CMake parts
# which have been generated by vcproj2cmake,
# then the next build run will immediately have directly integrated
# all the VS projects converted in the previous step.

function(v2cd_downloader_setup)
  include(ExternalProject OPTIONAL)

  if(NOT COMMAND ExternalProject_Add)
    # Either too old *or* too new, right?
    message("Could not detect a compatible ExternalProject CMake module. Are you using a suitable CMake version? ExternalProject_Add() not available, thus cannot automatically grab the requested vcproj2cmake installation.")
    return()
  endif(NOT COMMAND ExternalProject_Add)

  # We're not managing the *download* location - rather,
  # we're interested in *install* location only (we really couldn't care less
  # where EP places its downloads).
  # All we want is:
  # having things *fetched* properly,
  # *configured* for a non-destructive install (to a tree which already does
  # contain some configuration for V2C mechanism),
  # *installed* (via _default_ CMake install handling)
  # to where we'd want it to sit.
  # Finally, we add an *extra* step to actually have the converter run
  # if needed.
  set(v2c_ep_install_dir_default_setting_ "${CMAKE_SOURCE_DIR}/cmake/vcproj2cmake/temporary_content/")
  set(V2C_EP_INSTALL_DIR "${v2c_ep_install_dir_default_setting_}" CACHE PATH "Target directory for vcproj2cmake repository fetch.")
  set(v2c_ep_git_repository_default_setting_ "git://git.code.sf.net/p/vcproj2cmake/code")
  set(V2C_EP_GIT_REPOSITORY "${v2c_ep_git_repository_default_setting_}" CACHE STRING "vcproj2cmake git repository URL")
  set(V2C_EP_GIT_TAG experimental_unverified)

  if(GIT_EXECUTABLE) # provided by EP module...
    ExternalProject_Add(v2c_downloader
      GIT_REPOSITORY "${V2C_EP_GIT_REPOSITORY}"
      GIT_TAG "${V2C_EP_GIT_TAG}"
      #INSTALL_COMMAND echo hi
      LOG_DOWNLOAD 1
      LOG_INSTALL 1
    )

    ExternalProject_Add_Step(
      COMMAND ruby
      COMMENT
      DEPENDEES
      DEPENDERS
      LOG 1
    )
  else(GIT_EXECUTABLE)
    message("GIT_EXECUTABLE not available - cannot do git-based download via ExternalProject_Add().")
  endif(GIT_EXECUTABLE)
endfunction(v2cd_downloader_setup)

option(V2C_EP_WANT_DOWNLOAD "Have vcproj2cmake fetched automatically, directly from within this source tree?" ON)
if(V2C_EP_WANT_DOWNLOAD)
  v2cd_downloader_setup()
endif(V2C_EP_WANT_DOWNLOAD)
